### ISSUE TITLE
RFC: Introduce an interface for `Session` (v3 only)

### ISSUE THREAD

**Issue by cspray** [amphp/http-server-session#13]
I'd like to gauge the feasibility and willingness to introduce an interface for the `Session` class. There are 2 primary reasons I'd like this functionality:

1. Implementing the decorator pattern. There's functionality I'd like to provide on top of Amp's `Session`. An example of this is a "temporary" storage within the session that gets cleared out after use. I could provide my own interface for this functionality, but then I have to ensure this new API gets used everywhere and nobody uses Amp's Session directly. It would be better if I could decorate Amp's `Session` to provide this functionality and control what implementation gets injected as a dependency.
2. Testing. There are situations where it may be preferable to provide a stub or mock in Controller unit tests. This isn't currently possible.

Thanks for the Amp libraries and considering my idea!

**Comment by trowski** [comment]
This sounds reasonable to me.

**Comment by cspray** [comment]
Great. I can put together a PR for this. Would you prefer introducing something named `SessionInterface` or refactor the existing `Session` to the interface and rename the implementation something else? Typically I'm partial to not having `Interface` in the name but since we're already dealing with an existing library I don't want to introduce BC breaks unless ok to do so.

**Comment by trowski** [comment]
We never use `Interface` in any interface names. We can still have BC breaks in the beta, especially for something as easy to fix as a name. So definitely `Session` as the interface name, and… I dunno for the implementation, I'm terrible at naming things.

**Comment by kelunik** [comment]
We've already moved most logic into interfaces and outside of `Session` itself. Could you add some more details on what you're planning to add so we can discuss possible alternatives?

**Comment by cspray** [comment]
@kelunik Sorry, I didn't see your comment until after I submitted my PR. Please let me know if you have any questions after reviewing the patch. Thanks!

**Comment by cspray** [comment]
Ok, sorry it took so long to respond to this. I didn't mean to leave this in a broken state.

There are 3 uses cases I have that I believe would benefit from the `Session` being an interface.

1. Define expiry conditions on session values

I would like to have some values stored in the session on a purely temporary basis. The first time some condition is met, in my case when the value is first read, I want them to be removed from the session. I'm imagining a decorated `Session` implementation that would keep track of a keys effective lifetime. In my mind it makes more sense to define this when writing the value, akin to defining a TTL for a cached value at write time, rather then everywhere it might be read.

It might be possible to do this in the `SessionStorage` interface but from what I understand that writes an entire collection of session data and I need to define these conditions on values _within_ that collection.

2. Logging Session information in development/debugging

It might be useful when debugging tricky situations to turn on heavy or verbose logging. Providing a decorated `Session` implementation that logs every read and write could provide useful information.

3. Providing a simpler implementation for tests

This one is less of a concern than the others but unit tests on a `RequestHandler` might benefit from less setup required to get a working Session together. I have done some of these type of unit tests and the existing setup allows for this pretty easily, but it would remove a little bit of boiler plate and make for slightly more understandable tests.

**Comment by kelunik** [comment]
> Define expiry conditions on session values

You likely want to wrap `Session` for that in a separate object rather than implementing `Session` directly. That way you can also add your own methods which enforce passing a lifetime and only expose the methods you want your application to use.

> Logging Session information in development/debugging

A custom `SessionStorage` is perfect for that, all read and write calls will pass through it.

> Providing a simpler implementation for tests

I don't see how the implementation of `Session` can be any simpler for tests. For the code around, you might want to build an abstraction / some reusable glue code, so the same code isn't repeated all the time.

**Comment by trowski** [comment]
The ability to mock `Session` in tests was the main use-case I saw for having interfaces. You can use `SessionStorage` to make assertions, but this requires knowing some implementation details of `Session`. Being able to check for invocations on the `Session` object itself makes for easier to understand tests.

For other uses such as temporary storage, I agree with @kelunik, that should be done in a wrapper class providing your own interface rather than having what I would assume would be specific keys on `Session` that would have a TTL or flash behavior.

**Comment by kelunik** [comment]
> Being able to check for invocations on the Session object itself makes for easier to understand tests.

Usually you don't want to check the direct invocations in tests IMO. Do you have a test example? I'm happy to suggest improvements.

**Comment by trowski** [comment]
To check that the session was locked by calling `open()` or the ID was regenerated with `regenerate()` for example. There are other ways to check for this, but that's the most straightforward way. Opening/locking can be checked by asserting the mutex is locked and ID regeneration by a mock `SessionIdGenerator`, but again this requires knowing `Session` will make these calls.

**Comment by kelunik** [comment]
I've added an implementation for tests in https://github.com/amphp/http-server-session/commit/f29662ea313fdea26e1234d2d20853d0aa66e08c. Please have a look and give some feedback. Adding assertions for `regenerate()` isn't directly possible, but there are other ways to assert it.

**Comment by kelunik** [comment]
Also, if you have any better names for that implementation in mind, please let me know!
