### ISSUE TITLE
Reading and locking is not simultaneous

### ISSUE THREAD

**Issue by bwoebi** [amphp/http-server-session#8]
Every time we lock, we want to execute a simultaneous lock and read - or at least first lock and then read, but not the reverse.

However currently we first read and then lock, allowing data being potentially changed between the read and the lock and thus possibly resulting inconsistent session data.

https://github.com/amphp/http-server-session/blob/613a829b1f5e8b1627cb611985642a3d9576d52c/src/Session.php#L138-L142

It should be enough to swap the lock and read there, I'm however not 100% sure on that.

Also I am wondering whether there's any reason to separately lock and read - when do we ever want to lock, but not read? At least when opening a new session, we should either assume there will be no clashes, ever (= too unlikely) and don't need to lock that at all _or_ assume it may happen, but then we need to check too whether such a session already exists by reading that key. Thus all cases needing a lock I know of need a lock _and_ a read, which indicates we should just combine this into one single method. Also, some stores provide exactly this atomic guarantee, e.g. in mysql a transaction with `SELECT ... FOR UPDATE`, where a row is locked _by reading it_.

At least these were the original design considerations when writing AerysSession the first time. I'm interested in hearing what profit separation brings.

**Comment by bwoebi** [comment]
PIng @trowski as author of https://github.com/amphp/http-server-session/commit/f5820fb7b92abf26e157d963fa229c3cdcc2c627

**Comment by kelunik** [comment]
Closing, as that changed now.
